
name: Node.js CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.18.0]
    env:
      VUE_WEBSITE_URL: ${{secrets.VUE_WEBSITE_URL}}
    steps:
      - uses: actions/checkout@v3
        with:
          clean: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install PM2
        run: npm install -g pm2

      - run: npm install

      - run: cd ./frontend/ && npm install
      - run: cd ./frontend/ && npm run build
      - run: cd ./frontend/ && cp -r dist/ ../

      - name: Run PM2 command
        run: pm2 restart 0